# This is a basic workflow to help you get started with Actions

name: Deploy DEV WEB

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches:
      - next
      - main
    paths:
      - 'apps/web/**'
      - 'libs/shared/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_web:
    uses: ./.github/workflows/reusable-web-e2e.yml
    with:
      ee: true
    secrets: inherit

  deploy_web:
    needs: test_web
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    uses: ./.github/workflows/reusable-web-deploy.yml
    with:
      environment: Development
      react_app_api_url: https://dev.api.novu.co
      react_app_ws_url: https://dev.ws.novu.co
      react_app_webhook_url: https://dev.webhook.novu.co
      react_app_widget_embed_path: https://dev.embed.novu.co/embed.umd.min.js
      react_app_sentry_dsn: https://2b5160da86384949be4cc66679c54e79@o1161119.ingest.sentry.io/6250907
      react_app_environment: dev
      react_app_mail_server_domain: dev.inbound-mail.novu.co
      react_app_hubspot_embed: 44416662
      netlify_deploy_message: Dev deployment
      netlify_alias: dev
      netlify_gh_env: development
      netlify_site_id: 45396446-dc86-4ad6-81e4-86d3eb78d06f
    secrets: inherit

  publish_docker_image_web:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: 'image=moby/buildkit:v0.12.4'

      - name: Build docker image
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login autovendyrepo.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
          cd apps/web && docker buildx build --load --platform=linux/amd64,linux/arm64 --provenance=false -f ./Dockerfile -t novu-web ./../..
          docker tag novu-web autovendyrepo.azurecr.io/novu-web:1
          docker push autovendyrepo.azurecr.io/novu-web:1
    
    
